### ISSUE TITLE
refreshToken of OAuth2AuthorizationCodeManager doesn't work properly

### ISSUE THREAD

**Issue by DiegoPergolini** [fattureincloud/fattureincloud-js-sdk#80]
**Describe the bug**
The OAuth2AuthorizationCodeTokenResponse class returns undefined for all properties (tokenType, accessToken, redirectUri, expiresIn, refreshToken) when calling the refreshToken method of OAuth2AuthorizationCodeManager.

**Env info**
- Node version: **v20.11.0**
- JS SDK version: **2.0.17**

**To Reproduce**
Utilize the refreshToken method within OAuth2AuthorizationCodeManager to refresh an access token. The method does not await the asynchronous call properly, leading to the issue.

` var tokenObj = await oauth.refreshToken(json["refresh_token"]);
  console.log(tokenObj)`
  Produce this:
`OAuth2AuthorizationCodeTokenResponse {
  tokenType: undefined,
  accessToken: undefined,
  redirectUri: undefined,
  expiresIn: undefined,
  refreshToken: undefined
}
`

**Expected behavior**
refreshToken should return an instance of OAuth2AuthorizationCodeTokenResponse with all fields populated based on the API response.

**Additional context**
The issue seems to stem from not handling the promise returned by tokenRequest correctly in refreshToken. Proper promise resolution or async/await usage could fix this.
The portion of code that produce the error in the sdk:
```javascript
refreshToken(refreshToken) {
  const tokenUri = `${this.baseUri}/oauth/token`;

  const data = {
    grant_type: 'refresh_token',
    client_id: this.clientId,
    client_secret: this.clientSecret,
    refresh_token: refreshToken
  };

  // Directly returning the promise without waiting for its resolution
  const res = this.tokenRequest(tokenUri, data);
  return new OAuth2AuthorizationCodeTokenResponse(res.token_type, res.access_token, res.refresh_token, res.expires_in);
}

**Comment by emajo** [comment]
Hi @DiegoPergolini thanks for reporting this issue, we will fix it asap and we will include the fix in the next sdk release (in the next 1-2 weeks).

Thanks again,
Emanuele.

**Comment by DiegoPergolini** [comment]
Ok, thank you!

**Comment by emajo** [comment]
Hi @DiegoPergolini we released a new SDK version that fixes this bug, let us know if you encounter some other issue.

Thanks,
Emanuele.
