### ISSUE TITLE
Wrong Country ISO code for 'DE'

### ISSUE THREAD

**Issue by marcovittoriozacca** [fattureincloud/fattureincloud-js-sdk#96]
When creating an invoice sending the COUNTRY_ISO as 'DE', the invoice is generated with country "COSTA D'AVORIO"

**Comment by valmoz** [comment]
Hello @marcovittoriozacca 
this is not an issue related to the Javascript SDK.
I'll close this issue, feel free to reopen it in our [Community](https://github.com/fattureincloud/api/discussions) or by emailing info@fattureincloud.it; I suggest using the latter, so we can retrieve your company ID and check your API requests on our logs.

Thanks
Mauro
